/**
 * Embed WASM binary as base64 string in a TypeScript module.
 * Reads dist/engine.wasm → writes src/js/engine-wasm.generated.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const wasmPath = join(root, "dist", "engine.wasm");
const outPath = join(root, "src", "js", "engine-wasm.generated.ts");

const wasmBytes = readFileSync(wasmPath);
const b64 = wasmBytes.toString("base64");

writeFileSync(
  outPath,
  `// AUTO-GENERATED by scripts/embed-wasm.mjs — do not edit\nexport const wasmBase64 = "${b64}";\n`,
);

console.log(
  `✅ Embedded ${wasmBytes.length} bytes (${(b64.length / 1024).toFixed(1)} KB base64) → ${outPath}`,
);
